# Generated by Django 5.1.1 on 2024-09-25 07:50

import faunatrack.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faunatrack', '0002_coordonnee_projet_espece_status_alter_espece_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coordonnee',
            name='lattitude',
            field=models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=13, null=True, validators=[faunatrack.models.validate_lattitude, faunatrack.models.validate_lattidue_not_a_string]),
        ),
        migrations.AlterField(
            model_name='coordonnee',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=13, null=True, validators=[faunatrack.models.validate_longitude]),
        ),
    ]
