# Generated by Django 5.1.1 on 2024-09-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faunatrack', '0003_projet_slug_alter_coordonnee_lattitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
