# Generated by Django 5.1.1 on 2024-09-25 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faunatrack', '0004_alter_projet_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scientifique',
            options={'verbose_name': 'Utilisateur Faunatrack', 'verbose_name_plural': 'Utilisateurs Faunatrack'},
        ),
        migrations.AlterUniqueTogether(
            name='observation',
            unique_together={('espece', 'coordonnee')},
        ),
    ]
