# Generated by Django 5.1.1 on 2024-09-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faunatrack', '0005_alter_scientifique_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='images',
            field=models.ImageField(default=None, null=True, upload_to='obs_especes/'),
        ),
    ]
